Fixing travis config

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -121,6 +121,10 @@ else
 fi
 
 make clean all "CFLAGS=$CFLAGS" "EXTRA_INCLUDES+=-I$CLIENTREPO_3X/include" "EXTRA_LDFLAGS=$LDFLAGS"
+if [ $? -gt 0 ] ; then
+    echo "The build has failed...exiting"
+    exit 1
+fi
 test-cleanup
 
 headline()
